### ISSUE TITLE
Bot is down due to Discord API change.

### ISSUE THREAD

**Issue by JakeRabinowitz** [velvet-halation/mts-bot#123]
**Describe the bug**
Bot is down in Discord because you need to update your Discord.py version to 1.3.4.

This happened to all my bots (Spirebot, Time Eater, etc) at the same time, so I'm pretty sure it's the same issue. I just changed my requirements.txt to:

`discord.py==1.3.4 `

and that fixed it.

**Comment by runttekita** [comment]
thank uuu
