### ISSUE TITLE
Add mod tag to keyword command

### ISSUE THREAD

**Issue by alexdriedger** [velvet-halation/mts-bot#78]
The `?keyword` command returns the description of the keyword but does not tell you which mod it is from

**Comment by Alchyr** [comment]
that's because that information isn't properly exported. Due to keywords being added differently, there's no way to determine which mod they come from currently. When exported, the exporter simply exports ALL keywords, regardless of what mod (or basegame) it's from.

**Comment by runttekita** [comment]
thanks alchy, blame twanvl
